package net.mirrorloong.chineseweapons.init;

import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.*;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.event.lifecycle.FMLClientSetupEvent;
import net.mirrorloong.chineseweapons.item.*;
import net.mirrorloong.chineseweapons.ChineseweaponsMod;

import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.NeoForgeRegistries;
import net.neoforged.neoforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import java.util.Objects;

public class ChineseweaponsModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(BuiltInRegistries.ITEM, ChineseweaponsMod.MODID);
	public static final DeferredHolder<Item, Item> GOLDENMOUNTAINCHARACTERARMOR_HELMET = REGISTRY.register("golden_mountain_character_armor_helmet", GoldenmountaincharacterarmorItem.Helmet::new);
	public static final DeferredHolder<Item, Item> GOLDENMOUNTAINCHARACTERARMOR_CHESTPLATE = REGISTRY.register("golden_mountain_character_armor_chestplate", GoldenmountaincharacterarmorItem.Chestplate::new);
	public static final DeferredHolder<Item, Item> GOLDENMOUNTAINCHARACTERARMOR_LEGGINGS = REGISTRY.register("golden_mountain_character_armor_leggings", GoldenmountaincharacterarmorItem.Leggings::new);
	public static final DeferredHolder<Item, Item> GOLDENMOUNTAINCHARACTERARMOR_BOOTS = REGISTRY.register("golden_mountain_character_armor_boots", GoldenmountaincharacterarmorItem.Boots::new);
	public static final DeferredHolder<Item, Item> NETHERITEMOUNTAINCHARACTERARMOR_HELMET = REGISTRY.register("netherite_mountain_character_armor_helmet", NetheritemountaincharacterarmorItem.Helmet::new);
	public static final DeferredHolder<Item, Item> NETHERITEMOUNTAINCHARACTERARMOR_CHESTPLATE = REGISTRY.register("netherite_mountain_character_armor_chestplate", NetheritemountaincharacterarmorItem.Chestplate::new);
	public static final DeferredHolder<Item, Item> NETHERITEMOUNTAINCHARACTERARMOR_LEGGINGS = REGISTRY.register("netherite_mountain_character_armor_leggings", NetheritemountaincharacterarmorItem.Leggings::new);
	public static final DeferredHolder<Item, Item> NETHERITEMOUNTAINCHARACTERARMOR_BOOTS = REGISTRY.register("netherite_mountain_character_armor_boots", NetheritemountaincharacterarmorItem.Boots::new);
	public static final DeferredHolder<Item, Item> DIAMONDMOUNTAINCHARACTERARMOR_HELMET = REGISTRY.register("diamond_mountain_character_armor_helmet", DiamondmountaincharacterarmorItem.Helmet::new);
	public static final DeferredHolder<Item, Item> DIAMONDMOUNTAINCHARACTERARMOR_CHESTPLATE = REGISTRY.register("diamond_mountain_character_armor_chestplate", DiamondmountaincharacterarmorItem.Chestplate::new);
	public static final DeferredHolder<Item, Item> DIAMONDMOUNTAINCHARACTERARMOR_LEGGINGS = REGISTRY.register("diamond_mountain_character_armor_leggings", DiamondmountaincharacterarmorItem.Leggings::new);
	public static final DeferredHolder<Item, Item> DIAMONDMOUNTAINCHARACTERARMOR_BOOTS = REGISTRY.register("diamond_mountain_character_armor_boots", DiamondmountaincharacterarmorItem.Boots::new);
	public static final DeferredHolder<Item, Item> IRONMOUNTAINCHARACTERARMOR_HELMET = REGISTRY.register("iron_mountain_character_armor_helmet", IronmountaincharacterarmorItem.Helmet::new);
	public static final DeferredHolder<Item, Item> IRONMOUNTAINCHARACTERARMOR_CHESTPLATE = REGISTRY.register("iron_mountain_character_armor_chestplate", IronmountaincharacterarmorItem.Chestplate::new);
	public static final DeferredHolder<Item, Item> IRONMOUNTAINCHARACTERARMOR_LEGGINGS = REGISTRY.register("iron_mountain_character_armor_leggings", IronmountaincharacterarmorItem.Leggings::new);
	public static final DeferredHolder<Item, Item> IRONMOUNTAINCHARACTERARMOR_BOOTS = REGISTRY.register("iron_mountain_character_armor_boots", IronmountaincharacterarmorItem.Boots::new);
	public static final DeferredHolder<Item, Item> DIAMONDEARLYTANGDYNASTYMINGGUANGARMOR_HELMET = REGISTRY.register("diamond_early_tang_dynasty_ming_guang_armor_helmet", DiamondearlytangdynastymingguangarmorItem.Helmet::new);
	public static final DeferredHolder<Item, Item> DIAMONDEARLYTANGDYNASTYMINGGUANGARMOR_CHESTPLATE = REGISTRY.register("diamond_early_tang_dynasty_ming_guang_armor_chestplate", DiamondearlytangdynastymingguangarmorItem.Chestplate::new);
	public static final DeferredHolder<Item, Item> DIAMONDEARLYTANGDYNASTYMINGGUANGARMOR_LEGGINGS = REGISTRY.register("diamond_early_tang_dynasty_ming_guang_armor_leggings", DiamondearlytangdynastymingguangarmorItem.Leggings::new);
	public static final DeferredHolder<Item, Item> DIAMONDEARLYTANGDYNASTYMINGGUANGARMOR_BOOTS = REGISTRY.register("diamond_early_tang_dynasty_ming_guang_armor_boots", DiamondearlytangdynastymingguangarmorItem.Boots::new);
	public static final DeferredHolder<Item, Item> NETHERITEEARLYTANGDYNASTYMINGGUANGARMOR_HELMET = REGISTRY.register("netherite_early_tang_dynasty_ming_guang_armor_helmet", NetheriteearlytangdynastymingguangarmorItem.Helmet::new);
	public static final DeferredHolder<Item, Item> NETHERITEEARLYTANGDYNASTYMINGGUANGARMOR_CHESTPLATE = REGISTRY.register("netherite_early_tang_dynasty_ming_guang_armor_chestplate", NetheriteearlytangdynastymingguangarmorItem.Chestplate::new);
	public static final DeferredHolder<Item, Item> NETHERITEEARLYTANGDYNASTYMINGGUANGARMOR_LEGGINGS = REGISTRY.register("netherite_early_tang_dynasty_ming_guang_armor_leggings", NetheriteearlytangdynastymingguangarmorItem.Leggings::new);
	public static final DeferredHolder<Item, Item> NETHERITEEARLYTANGDYNASTYMINGGUANGARMOR_BOOTS = REGISTRY.register("netherite_early_tang_dynasty_ming_guang_armor_boots", NetheriteearlytangdynastymingguangarmorItem.Boots::new);
	public static final DeferredHolder<Item, Item> IRONEARLYTANGDYNASTYMINGGUANGARMOR_HELMET = REGISTRY.register("iron_early_tang_dynasty_ming_guang_armor_helmet", IronearlytangdynastymingguangarmorItem.Helmet::new);
	public static final DeferredHolder<Item, Item> IRONEARLYTANGDYNASTYMINGGUANGARMOR_CHESTPLATE = REGISTRY.register("iron_early_tang_dynasty_ming_guang_armor_chestplate", IronearlytangdynastymingguangarmorItem.Chestplate::new);
	public static final DeferredHolder<Item, Item> IRONEARLYTANGDYNASTYMINGGUANGARMOR_LEGGINGS = REGISTRY.register("iron_early_tang_dynasty_ming_guang_armor_leggings", IronearlytangdynastymingguangarmorItem.Leggings::new);
	public static final DeferredHolder<Item, Item> IRONEARLYTANGDYNASTYMINGGUANGARMOR_BOOTS = REGISTRY.register("iron_early_tang_dynasty_ming_guang_armor_boots", IronearlytangdynastymingguangarmorItem.Boots::new);
	public static final DeferredHolder<Item, Item> GOLDENEARLYTANGDYNASTYMINGGUANGARMOR_HELMET = REGISTRY.register("golden_early_tang_dynasty_ming_guang_armor_helmet", GoldenearlytangdynastymingguangarmorItem.Helmet::new);
	public static final DeferredHolder<Item, Item> GOLDENEARLYTANGDYNASTYMINGGUANGARMOR_CHESTPLATE = REGISTRY.register("golden_early_tang_dynasty_ming_guang_armor_chestplate", GoldenearlytangdynastymingguangarmorItem.Chestplate::new);
	public static final DeferredHolder<Item, Item> GOLDENEARLYTANGDYNASTYMINGGUANGARMOR_LEGGINGS = REGISTRY.register("golden_early_tang_dynasty_ming_guang_armor_leggings", GoldenearlytangdynastymingguangarmorItem.Leggings::new);
	public static final DeferredHolder<Item, Item> GOLDENEARLYTANGDYNASTYMINGGUANGARMOR_BOOTS = REGISTRY.register("golden_early_tang_dynasty_ming_guang_armor_boots", GoldenearlytangdynastymingguangarmorItem.Boots::new);
    public static final DeferredHolder<Item, Item> IRONFOOTMENARMOR_HELMET = REGISTRY.register("iron_footmen_armor_helmet", IronfootmenarmorItem.Helmet::new);
    public static final DeferredHolder<Item, Item> IRONFOOTMENARMOR_CHESTPLATE = REGISTRY.register("iron_footmen_armor_chestplate", IronfootmenarmorItem.Chestplate::new);
    public static final DeferredHolder<Item, Item> IRONFOOTMENARMOR_LEGGINGS = REGISTRY.register("iron_footmen_armor_leggings", IronfootmenarmorItem.Leggings::new);
    public static final DeferredHolder<Item, Item> IRONFOOTMENARMOR_BOOTS = REGISTRY.register("iron_footmen_armor_boots", IronfootmenarmorItem.Boots::new);
    public static final DeferredHolder<Item, Item> GOLDENFOOTMENARMOR_HELMET = REGISTRY.register("golden_footmen_armor_helmet", GoldenfootmenarmorItem.Helmet::new);
    public static final DeferredHolder<Item, Item> GOLDENFOOTMENARMOR_CHESTPLATE = REGISTRY.register("golden_footmen_armor_chestplate", GoldenfootmenarmorItem.Chestplate::new);
    public static final DeferredHolder<Item, Item> GOLDENFOOTMENARMOR_LEGGINGS = REGISTRY.register("golden_footmen_armor_leggings", GoldenfootmenarmorItem.Leggings::new);
    public static final DeferredHolder<Item, Item> GOLDENFOOTMENARMOR_BOOTS = REGISTRY.register("golden_footmen_armor_boots", GoldenfootmenarmorItem.Boots::new);
    public static final DeferredHolder<Item, Item> DIAMONDFOOTMENARMOR_HELMET = REGISTRY.register("diamond_footmen_armor_helmet", DiamondfootmenarmorItem.Helmet::new);
    public static final DeferredHolder<Item, Item> DIAMONDFOOTMENARMOR_CHESTPLATE = REGISTRY.register("diamond_footmen_armor_chestplate", DiamondfootmenarmorItem.Chestplate::new);
    public static final DeferredHolder<Item, Item> DIAMONDFOOTMENARMOR_LEGGINGS = REGISTRY.register("diamond_footmen_armor_leggings", DiamondfootmenarmorItem.Leggings::new);
    public static final DeferredHolder<Item, Item> DIAMONDFOOTMENARMOR_BOOTS = REGISTRY.register("diamond_footmen_armor_boots", DiamondfootmenarmorItem.Boots::new);
    public static final DeferredHolder<Item, Item> NETHERITEFOOTMENARMOR_HELMET = REGISTRY.register("netherite_footmen_armor_helmet", NetheritefootmenarmorItem.Helmet::new);
    public static final DeferredHolder<Item, Item> NETHERITEFOOTMENARMOR_CHESTPLATE = REGISTRY.register("netherite_footmen_armor_chestplate", NetheritefootmenarmorItem.Chestplate::new);
    public static final DeferredHolder<Item, Item> NETHERITEFOOTMENARMOR_LEGGINGS = REGISTRY.register("netherite_footmen_armor_leggings", NetheritefootmenarmorItem.Leggings::new);
    public static final DeferredHolder<Item, Item> NETHERITEFOOTMENARMOR_BOOTS = REGISTRY.register("netherite_footmen_armor_boots", NetheritefootmenarmorItem.Boots::new);
	public static final DeferredHolder<Item, Item> GOLDENBLACKCHUIARMOR_HELMET = REGISTRY.register("golden_black_chui_armor_helmet", GoldenblackchuiarmorItem.Helmet::new);
	public static final DeferredHolder<Item, Item> GOLDENBLACKCHUIARMOR_CHESTPLATE = REGISTRY.register("golden_black_chui_armor_chestplate", GoldenblackchuiarmorItem.Chestplate::new);
	public static final DeferredHolder<Item, Item> GOLDENBLACKCHUIARMOR_LEGGINGS = REGISTRY.register("golden_black_chui_armor_leggings", GoldenblackchuiarmorItem.Leggings::new);
	public static final DeferredHolder<Item, Item> GOLDENBLACKCHUIARMOR_BOOTS = REGISTRY.register("golden_black_chui_armor_boots", GoldenblackchuiarmorItem.Boots::new);
	public static final DeferredHolder<Item, Item> DIAMONDBLACKCHUIARMOR_HELMET = REGISTRY.register("diamond_black_chui_armor_helmet", DiamondblackchuiarmorItem.Helmet::new);
	public static final DeferredHolder<Item, Item> DIAMONDBLACKCHUIARMOR_CHESTPLATE = REGISTRY.register("diamond_black_chui_armor_chestplate", DiamondblackchuiarmorItem.Chestplate::new);
	public static final DeferredHolder<Item, Item> DIAMONDBLACKCHUIARMOR_LEGGINGS = REGISTRY.register("diamond_black_chui_armor_leggings", DiamondblackchuiarmorItem.Leggings::new);
	public static final DeferredHolder<Item, Item> DIAMONDBLACKCHUIARMOR_BOOTS = REGISTRY.register("diamond_black_chui_armor_boots", DiamondblackchuiarmorItem.Boots::new);
	public static final DeferredHolder<Item, Item> NETHERITEBLACKCHUIARMOR_HELMET = REGISTRY.register("netherite_black_chui_armor_helmet", NetheriteblackchuiarmorItem.Helmet::new);
	public static final DeferredHolder<Item, Item> NETHERITEBLACKCHUIARMOR_CHESTPLATE = REGISTRY.register("netherite_black_chui_armor_chestplate", NetheriteblackchuiarmorItem.Chestplate::new);
	public static final DeferredHolder<Item, Item> NETHERITEBLACKCHUIARMOR_LEGGINGS = REGISTRY.register("netherite_black_chui_armor_leggings", NetheriteblackchuiarmorItem.Leggings::new);
	public static final DeferredHolder<Item, Item> NETHERITEBLACKCHUIARMOR_BOOTS = REGISTRY.register("netherite_black_chui_armor_boots", NetheriteblackchuiarmorItem.Boots::new);
	public static final DeferredHolder<Item, Item> IRONBLACKCHUIARMOR_HELMET = REGISTRY.register("iron_black_chui_armor_helmet", IronblackchuiarmorItem.Helmet::new);
	public static final DeferredHolder<Item, Item> IRONBLACKCHUIARMOR_CHESTPLATE = REGISTRY.register("iron_black_chui_armor_chestplate", IronblackchuiarmorItem.Chestplate::new);
	public static final DeferredHolder<Item, Item> IRONBLACKCHUIARMOR_LEGGINGS = REGISTRY.register("iron_black_chui_armor_leggings", IronblackchuiarmorItem.Leggings::new);
	public static final DeferredHolder<Item, Item> IRONBLACKCHUIARMOR_BOOTS = REGISTRY.register("iron_black_chui_armor_boots", IronblackchuiarmorItem.Boots::new);
	public static final DeferredHolder<Item, Item> GOLDENMIDDLETANGDYNASTYMINGGUANGARMOR_HELMET = REGISTRY.register("golden_middle_tang_dynasty_ming_guang_armor_helmet", GoldenmiddletangdynastymingguangarmorItem.Helmet::new);
	public static final DeferredHolder<Item, Item> GOLDENMIDDLETANGDYNASTYMINGGUANGARMOR_CHESTPLATE = REGISTRY.register("golden_middle_tang_dynasty_ming_guang_armor_chestplate", GoldenmiddletangdynastymingguangarmorItem.Chestplate::new);
	public static final DeferredHolder<Item, Item> GOLDENMIDDLETANGDYNASTYMINGGUANGARMOR_LEGGINGS = REGISTRY.register("golden_middle_tang_dynasty_ming_guang_armor_leggings", GoldenmiddletangdynastymingguangarmorItem.Leggings::new);
	public static final DeferredHolder<Item, Item> GOLDENMIDDLETANGDYNASTYMINGGUANGARMOR_BOOTS = REGISTRY.register("golden_middle_tang_dynasty_ming_guang_armor_boots", GoldenmiddletangdynastymingguangarmorItem.Boots::new);
	public static final DeferredHolder<Item, Item> IRONMIDDLETANGDYNASTYMINGGUANGARMOR_HELMET = REGISTRY.register("iron_middle_tang_dynasty_ming_guang_armor_helmet", IronmiddletangdynastymingguangarmorItem.Helmet::new);
	public static final DeferredHolder<Item, Item> IRONMIDDLETANGDYNASTYMINGGUANGARMOR_CHESTPLATE = REGISTRY.register("iron_middle_tang_dynasty_ming_guang_armor_chestplate", IronmiddletangdynastymingguangarmorItem.Chestplate::new);
	public static final DeferredHolder<Item, Item> IRONMIDDLETANGDYNASTYMINGGUANGARMOR_LEGGINGS = REGISTRY.register("iron_middle_tang_dynasty_ming_guang_armor_leggings", IronmiddletangdynastymingguangarmorItem.Leggings::new);
	public static final DeferredHolder<Item, Item> IRONMIDDLETANGDYNASTYMINGGUANGARMOR_BOOTS = REGISTRY.register("iron_middle_tang_dynasty_ming_guang_armor_boots", IronmiddletangdynastymingguangarmorItem.Boots::new);
	public static final DeferredHolder<Item, Item> NETHERITEMIDDLETANGDYNASTYMINGGUANGARMOR_HELMET = REGISTRY.register("netherite_middle_tang_dynasty_ming_guang_armor_helmet", NetheritemiddletangdynastymingguangarmorItem.Helmet::new);
	public static final DeferredHolder<Item, Item> NETHERITEMIDDLETANGDYNASTYMINGGUANGARMOR_CHESTPLATE = REGISTRY.register("netherite_middle_tang_dynasty_ming_guang_armor_chestplate", NetheritemiddletangdynastymingguangarmorItem.Chestplate::new);
	public static final DeferredHolder<Item, Item> NETHERITEMIDDLETANGDYNASTYMINGGUANGARMOR_LEGGINGS = REGISTRY.register("netherite_middle_tang_dynasty_ming_guang_armor_leggings", NetheritemiddletangdynastymingguangarmorItem.Leggings::new);
	public static final DeferredHolder<Item, Item> NETHERITEMIDDLETANGDYNASTYMINGGUANGARMOR_BOOTS = REGISTRY.register("netherite_middle_tang_dynasty_ming_guang_armor_boots", NetheritemiddletangdynastymingguangarmorItem.Boots::new);
	public static final DeferredHolder<Item, Item> DIAMONDMIDDLETANGDYNASTYMINGGUANGARMOR_HELMET = REGISTRY.register("diamond_middle_tang_dynasty_ming_guang_armor_helmet", DiamondmiddletangdynastymingguangarmorItem.Helmet::new);
	public static final DeferredHolder<Item, Item> DIAMONDMIDDLETANGDYNASTYMINGGUANGARMOR_CHESTPLATE = REGISTRY.register("diamond_middle_tang_dynasty_ming_guang_armor_chestplate", DiamondmiddletangdynastymingguangarmorItem.Chestplate::new);
	public static final DeferredHolder<Item, Item> DIAMONDMIDDLETANGDYNASTYMINGGUANGARMOR_LEGGINGS = REGISTRY.register("diamond_middle_tang_dynasty_ming_guang_armor_leggings", DiamondmiddletangdynastymingguangarmorItem.Leggings::new);
	public static final DeferredHolder<Item, Item> DIAMONDMIDDLETANGDYNASTYMINGGUANGARMOR_BOOTS = REGISTRY.register("diamond_middle_tang_dynasty_ming_guang_armor_boots", DiamondmiddletangdynastymingguangarmorItem.Boots::new);
	public static final DeferredHolder<Item, Item> TANGDYNASTYINFANTRYARMOR_HELMET = REGISTRY.register("tang_dynasty_infantry_armor_helmet", TangdynastyinfantryarmorItem.Helmet::new);
	public static final DeferredHolder<Item, Item> TANGDYNASTYINFANTRYARMOR_CHESTPLATE = REGISTRY.register("tang_dynasty_infantry_armor_chestplate", TangdynastyinfantryarmorItem.Chestplate::new);
	public static final DeferredHolder<Item, Item> TANGDYNASTYINFANTRYARMOR_LEGGINGS = REGISTRY.register("tang_dynasty_infantry_armor_leggings", TangdynastyinfantryarmorItem.Leggings::new);
	public static final DeferredHolder<Item, Item> TANGDYNASTYINFANTRYARMOR_BOOTS = REGISTRY.register("tang_dynasty_infantry_armor_boots", TangdynastyinfantryarmorItem.Boots::new);
	public static final DeferredHolder<Item, Item> IRONFINE_SCALE_ARMOR_HELMET = REGISTRY.register("iron_fine_scale_armor_helmet", () -> new FinescalearmorItem(FinescalearmorItem.MaterialVariant.IRON, ArmorItem.Type.HELMET));
	public static final DeferredHolder<Item, Item> IRONFINE_SCALE_ARMOR_CHESTPLATE = REGISTRY.register("iron_fine_scale_armor_chestplate", () -> new FinescalearmorItem(FinescalearmorItem.MaterialVariant.IRON, ArmorItem.Type.CHESTPLATE));
	public static final DeferredHolder<Item, Item> IRONFINE_SCALE_ARMOR_LEGGINGS = REGISTRY.register("iron_fine_scale_armor_leggings", () -> new FinescalearmorItem(FinescalearmorItem.MaterialVariant.IRON, ArmorItem.Type.LEGGINGS));
	public static final DeferredHolder<Item, Item> IRONFINE_SCALE_ARMOR_BOOTS = REGISTRY.register("iron_fine_scale_armor_boots", () -> new FinescalearmorItem(FinescalearmorItem.MaterialVariant.IRON, ArmorItem.Type.BOOTS));
	public static final DeferredHolder<Item, Item> GOLDENFINE_SCALE_ARMOR_HELMET = REGISTRY.register("golden_fine_scale_armor_helmet", () -> new FinescalearmorItem(FinescalearmorItem.MaterialVariant.GOLDEN, ArmorItem.Type.HELMET));
	public static final DeferredHolder<Item, Item> GOLDENFINE_SCALE_ARMOR_CHESTPLATE = REGISTRY.register("golden_fine_scale_armor_chestplate", () -> new FinescalearmorItem(FinescalearmorItem.MaterialVariant.GOLDEN, ArmorItem.Type.CHESTPLATE));
	public static final DeferredHolder<Item, Item> GOLDENFINE_SCALE_ARMOR_LEGGINGS = REGISTRY.register("golden_fine_scale_armor_leggings", () -> new FinescalearmorItem(FinescalearmorItem.MaterialVariant.GOLDEN, ArmorItem.Type.LEGGINGS));
	public static final DeferredHolder<Item, Item> GOLDENFINE_SCALE_ARMOR_BOOTS = REGISTRY.register("golden_fine_scale_armor_boots", () -> new FinescalearmorItem(FinescalearmorItem.MaterialVariant.GOLDEN, ArmorItem.Type.BOOTS));
	public static final DeferredHolder<Item, Item> DIAMONDFINE_SCALE_ARMOR_HELMET = REGISTRY.register("diamond_fine_scale_armor_helmet", () -> new FinescalearmorItem(FinescalearmorItem.MaterialVariant.DIAMOND, ArmorItem.Type.HELMET));
	public static final DeferredHolder<Item, Item> DIAMONDFINE_SCALE_ARMOR_CHESTPLATE = REGISTRY.register("diamond_fine_scale_armor_chestplate", () -> new FinescalearmorItem(FinescalearmorItem.MaterialVariant.DIAMOND, ArmorItem.Type.CHESTPLATE));
	public static final DeferredHolder<Item, Item> DIAMONDFINE_SCALE_ARMOR_LEGGINGS = REGISTRY.register("diamond_fine_scale_armor_leggings", () -> new FinescalearmorItem(FinescalearmorItem.MaterialVariant.DIAMOND, ArmorItem.Type.LEGGINGS));
	public static final DeferredHolder<Item, Item> DIAMONDFINE_SCALE_ARMOR_BOOTS = REGISTRY.register("diamond_fine_scale_armor_boots", () -> new FinescalearmorItem(FinescalearmorItem.MaterialVariant.DIAMOND, ArmorItem.Type.BOOTS));
	public static final DeferredHolder<Item, Item> NETHERITEFINE_SCALE_ARMOR_HELMET = REGISTRY.register("netherite_fine_scale_armor_helmet", () -> new FinescalearmorItem(FinescalearmorItem.MaterialVariant.NETHERITE, ArmorItem.Type.HELMET));
	public static final DeferredHolder<Item, Item> NETHERITEFINE_SCALE_ARMOR_CHESTPLATE = REGISTRY.register("netherite_fine_scale_armor_chestplate", () -> new FinescalearmorItem(FinescalearmorItem.MaterialVariant.NETHERITE, ArmorItem.Type.CHESTPLATE));
	public static final DeferredHolder<Item, Item> NETHERITEFINE_SCALE_ARMOR_LEGGINGS = REGISTRY.register("netherite_fine_scale_armor_leggings", () -> new FinescalearmorItem(FinescalearmorItem.MaterialVariant.NETHERITE, ArmorItem.Type.LEGGINGS));
	public static final DeferredHolder<Item, Item> NETHERITEFINE_SCALE_ARMOR_BOOTS = REGISTRY.register("netherite_fine_scale_armor_boots", () -> new FinescalearmorItem(FinescalearmorItem.MaterialVariant.NETHERITE, ArmorItem.Type.BOOTS));
    //铁=a，石=a-1，木=a-2，金伤害=a-2，钻石=a+1
	public static final DeferredHolder<Item, Item> GOLDEN_DAGGER_AXE = REGISTRY.register("golden_dagger_axe", GoldendaggeraxeItem::new);
	public static final DeferredHolder<Item, Item> DIAMOND_DAGGER_AXE = REGISTRY.register("diamond_dagger_axe", DiamonddaggeraxeItem::new);
	public static final DeferredHolder<Item, Item> IRON_DAGGER_AXE = REGISTRY.register("iron_dagger_axe", IrondaggeraxeItem::new);
	public static final DeferredHolder<Item, Item> WOODEN_DAGGER_AXE = REGISTRY.register("wooden_dagger_axe", WoodendaggeraxeItem::new);
	public static final DeferredHolder<Item, Item> NETHERITE_DAGGER_AXE = REGISTRY.register("netherite_dagger_axe", NetheritedaggeraxeItem::new);
	public static final DeferredHolder<Item, Item> STONE_DAGGER_AXE = REGISTRY.register("stone_dagger_axe", StonedaggeraxeItem::new);

	public static final DeferredHolder<Item, Item> DIAMOND_GLAIVE = REGISTRY.register("diamond_glaive", DiamondglaiveItem::new);
	public static final DeferredHolder<Item, Item> GOLDEN_GLAIVE = REGISTRY.register("golden_glaive", GoldenglaiveItem::new);
	public static final DeferredHolder<Item, Item> NETHERITE_GLAIVE = REGISTRY.register("netherite_glaive", NetheriteglaiveItem::new);
	public static final DeferredHolder<Item, Item> IRON_GLAIVE = REGISTRY.register("iron_glaive", IronglaiveItem::new);
	public static final DeferredHolder<Item, Item> STONE_GLAIVE = REGISTRY.register("stone_glaive", StoneglaiveItem::new);
	public static final DeferredHolder<Item, Item> WOODEN_GLAIVE = REGISTRY.register("wooden_glaive", WoodenglaiveItem::new);
	public static final DeferredHolder<Item, Item> GREENLOONG_GLAIVE = REGISTRY.register("green_loong_glaive", GreenloongglaiveItem::new);

    public static final DeferredHolder<Item, Item> DIAMOND_TANG_DYNASTY_HENG_SABER = REGISTRY.register("diamond_tang_dynasty_heng_saber", () -> new TangDynastyHengSaberItem(Tiers.DIAMOND, 8, 1.4F,false));
    public static final DeferredHolder<Item, Item> GOLDEN_TANG_DYNASTY_HENG_SABER = REGISTRY.register("golden_tang_dynasty_heng_saber", () -> new TangDynastyHengSaberItem(Tiers.GOLD, 5, 1.8F,false));
    public static final DeferredHolder<Item, Item> NETHERITE_TANG_DYNASTY_HENG_SABER = REGISTRY.register("netherite_tang_dynasty_heng_saber", () -> new TangDynastyHengSaberItem(Tiers.NETHERITE, 9, 1.4F,true));
    public static final DeferredHolder<Item, Item> IRON_TANG_DYNASTY_HENG_SABER = REGISTRY.register("iron_tang_dynasty_heng_saber", () -> new TangDynastyHengSaberItem(Tiers.IRON, 7, 1.6F,false));
    public static final DeferredHolder<Item, Item> STONE_TANG_DYNASTY_HENG_SABER = REGISTRY.register("stone_tang_dynasty_heng_saber", () -> new TangDynastyHengSaberItem(Tiers.STONE, 6, 1.6F,false));
    public static final DeferredHolder<Item, Item> WOODEN_TANG_DYNASTY_HENG_SABER = REGISTRY.register("wooden_tang_dynasty_heng_saber", () -> new TangDynastyHengSaberItem(Tiers.WOOD, 5, 1.8F,false));

	public static final DeferredHolder<Item, Item> WOODEN_SKY_PIERCING_HALBERD = REGISTRY.register("wooden_sky_piercing_halberd", () -> new SkyPiercingHalberdItem(Tiers.WOOD, 4, 1.4F,false));
	public static final DeferredHolder<Item, Item> STONE_SKY_PIERCING_HALBERD = REGISTRY.register("stone_sky_piercing_halberd", () -> new SkyPiercingHalberdItem(Tiers.STONE, 5, 1.4F,false));
	public static final DeferredHolder<Item, Item> GOLDEN_SKY_PIERCING_HALBERD = REGISTRY.register("golden_sky_piercing_halberd", () -> new SkyPiercingHalberdItem(Tiers.GOLD, 4, 1.4F,false));
	public static final DeferredHolder<Item, Item> IRON_SKY_PIERCING_HALBERD = REGISTRY.register("iron_sky_piercing_halberd", () -> new SkyPiercingHalberdItem(Tiers.IRON, 6, 1.2F,false));
	public static final DeferredHolder<Item, Item> DIAMOND_SKY_PIERCING_HALBERD = REGISTRY.register("diamond_sky_piercing_halberd", () -> new SkyPiercingHalberdItem(Tiers.DIAMOND, 7, 1.2F,false));
	public static final DeferredHolder<Item, Item> NETHERITE_SKY_PIERCING_HALBERD = REGISTRY.register("netherite_sky_piercing_halberd", () -> new SkyPiercingHalberdItem(Tiers.NETHERITE, 8, 1F,true));

	public static final DeferredHolder<Item, Item> ARMOR_CASTING_TABLE = block(ChineseweaponsModBlocks.ARMOR_CASTING_TABLE);
	public static final DeferredHolder<Item, Item> DiamondArmorPieces = REGISTRY.register("diamond_armor_pieces", () -> new Item(new Item.Properties()));
	public static final DeferredHolder<Item, Item> DiamondArmorPiecesPlate = REGISTRY.register("diamond_armor_pieces_plate", () -> new Item(new Item.Properties()));
	public static final DeferredHolder<Item, Item> DiamondMountainCharacterArmorPiecesPlate = REGISTRY.register("diamond_mountain_character_armor_pieces_plate", () -> new Item(new Item.Properties()));
	public static final DeferredHolder<Item, Item> GoldenArmorPieces = REGISTRY.register("golden_armor_pieces", () -> new Item(new Item.Properties()));
	public static final DeferredHolder<Item, Item> GoldenArmorPiecesPlate = REGISTRY.register("golden_armor_pieces_plate", () -> new Item(new Item.Properties()));
    public static final DeferredHolder<Item, Item> GoldenMountainCharacterArmorPieces = REGISTRY.register("golden_mountain_character_armor_pieces", () -> new Item(new Item.Properties()));
    public static final DeferredHolder<Item, Item> GoldenMountainCharacterArmorPiecesPlate = REGISTRY.register("golden_mountain_character_armor_pieces_plate", () -> new Item(new Item.Properties()));
    public static final DeferredHolder<Item, Item> IronMountainCharacterArmorPieces = REGISTRY.register("iron_mountain_character_armor_pieces", () -> new Item(new Item.Properties()));
	public static final DeferredHolder<Item, Item> IronMountainCharacterArmorPiecesPlate = REGISTRY.register("iron_mountain_character_armor_pieces_plate", () -> new Item(new Item.Properties()));
	public static final DeferredHolder<Item, Item> StoneArmorPieces = REGISTRY.register("stone_armor_pieces", () -> new Item(new Item.Properties()));
	public static final DeferredHolder<Item, Item> StoneArmorPiecesPlate = REGISTRY.register("stone_armor_pieces_plate", () -> new Item(new Item.Properties()));
	public static final DeferredHolder<Item, Item> AncientGem = REGISTRY.register("ancient_gem",()->new Item(new Item.Properties()));
	public static final DeferredHolder<Item, Item> IronArmorPieces = REGISTRY.register("iron_armor_pieces",()->new Item(new Item.Properties()));
    public static final DeferredHolder<Item, Item> IronArmorPiecesPlate = REGISTRY.register("iron_armor_pieces_plate", () -> new Item(new Item.Properties()));
	public static final DeferredHolder<Item, Item> DiamondMountainCharacterArmorPieces = REGISTRY.register("diamond_mountain_character_armor_pieces",()->new Item(new Item.Properties()));
    public static final DeferredHolder<Item, Item> ANCIENT_GEM_ORE = block(ChineseweaponsModBlocks.ANCIENT_GEM_ORE);
    public static final DeferredHolder<Item, Item> DeepslateANCIENT_GEM_ORE = block(ChineseweaponsModBlocks.DeepslateANCIENT_GEM_ORE);
    public static final DeferredHolder<Item, Item> EarlyTangDynastyMingGuangArmorforgingStone = REGISTRY.register("early_tang_dynasty_ming_guang_armor_forging_stone", EarlyTangDynastyMingGuangArmorforgingStone::new);
    public static final DeferredHolder<Item, Item> FootmenArmorforgingStone = REGISTRY.register("footmen_armor_forging_stone", FootmenArmorforgingStone::new);
	public static final DeferredHolder<Item, Item> TangDynastyInfantryArmorforgingStone = REGISTRY.register("tang_dynasty_infantry_armor_forging_stone", TangDynastyInfantryArmorforgingStone::new);
	public static final DeferredHolder<Item, Item> FineScaleArmorforgingStone = REGISTRY.register("fine_scale_armor_forging_stone", FineScaleArmorforgingStone::new);
	public static final DeferredHolder<Item, Item> LateTangDynastyMingGuangArmorforgingStone = REGISTRY.register("late_tang_dynasty_ming_guang_armor_forging_stone", LateTangDynastyMingGuangArmorforgingStone::new);
    public static final DeferredHolder<Item, Item> MiddleTangDynastyMingGuangArmorforgingStone = REGISTRY.register("middle_tang_dynasty_ming_guang_armor_forging_stone", MiddleTangDynastyMingGuangArmorforgingStone::new);
    public static final DeferredHolder<Item, Item> MountainCharacterArmorforgingStone = REGISTRY.register("mountain_character_armor_forging_stone", MountainCharacterArmorforgingStone::new);
    public static final DeferredHolder<Item, Item> BlackChuiArmorforgingStone = REGISTRY.register("black_chui_armor_forging_stone", BlackChuiArmorforgingStone::new);
    public static final DeferredHolder<Item, Item> DIAMONDLATETANGDYNASTYMINGGUANGARMOR_HELMET = REGISTRY.register("diamond_late_tang_dynasty_ming_guang_armor_helmet", DiamondlatetangdynastymingguangarmorItem.Helmet::new);
    public static final DeferredHolder<Item, Item> DIAMONDLATETANGDYNASTYMINGGUANGARMOR_CHESTPLATE = REGISTRY.register("diamond_late_tang_dynasty_ming_guang_armor_chestplate", DiamondlatetangdynastymingguangarmorItem.Chestplate::new);
    public static final DeferredHolder<Item, Item> DIAMONDLATETANGDYNASTYMINGGUANGARMOR_LEGGINGS = REGISTRY.register("diamond_late_tang_dynasty_ming_guang_armor_leggings", DiamondlatetangdynastymingguangarmorItem.Leggings::new);
    public static final DeferredHolder<Item, Item> DIAMONDLATETANGDYNASTYMINGGUANGARMOR_BOOTS = REGISTRY.register("diamond_late_tang_dynasty_ming_guang_armor_boots", DiamondlatetangdynastymingguangarmorItem.Boots::new);
    public static final DeferredHolder<Item, Item> GOLDENLATETANGDYNASTYMINGGUANGARMOR_HELMET = REGISTRY.register("golden_late_tang_dynasty_ming_guang_armor_helmet", GoldenlatetangdynastymingguangarmorItem.Helmet::new);
    public static final DeferredHolder<Item, Item> GOLDENLATETANGDYNASTYMINGGUANGARMOR_CHESTPLATE = REGISTRY.register("golden_late_tang_dynasty_ming_guang_armor_chestplate", GoldenlatetangdynastymingguangarmorItem.Chestplate::new);
    public static final DeferredHolder<Item, Item> GOLDENLATETANGDYNASTYMINGGUANGARMOR_LEGGINGS = REGISTRY.register("golden_late_tang_dynasty_ming_guang_armor_leggings", GoldenlatetangdynastymingguangarmorItem.Leggings::new);
    public static final DeferredHolder<Item, Item> GOLDENLATETANGDYNASTYMINGGUANGARMOR_BOOTS = REGISTRY.register("golden_late_tang_dynasty_ming_guang_armor_boots", GoldenlatetangdynastymingguangarmorItem.Boots::new);
    public static final DeferredHolder<Item, Item> IRONLATETANGDYNASTYMINGGUANGARMOR_HELMET = REGISTRY.register("iron_late_tang_dynasty_ming_guang_armor_helmet", IronlatetangdynastymingguangarmorItem.Helmet::new);
    public static final DeferredHolder<Item, Item> IRONLATETANGDYNASTYMINGGUANGARMOR_CHESTPLATE = REGISTRY.register("iron_late_tang_dynasty_ming_guang_armor_chestplate", IronlatetangdynastymingguangarmorItem.Chestplate::new);
    public static final DeferredHolder<Item, Item> IRONLATETANGDYNASTYMINGGUANGARMOR_LEGGINGS = REGISTRY.register("iron_late_tang_dynasty_ming_guang_armor_leggings", IronlatetangdynastymingguangarmorItem.Leggings::new);
    public static final DeferredHolder<Item, Item> IRONLATETANGDYNASTYMINGGUANGARMOR_BOOTS = REGISTRY.register("iron_late_tang_dynasty_ming_guang_armor_boots", IronlatetangdynastymingguangarmorItem.Boots::new);
    public static final DeferredHolder<Item, Item> NETHERITELATETANGDYNASTYMINGGUANGARMOR_HELMET = REGISTRY.register("netherite_late_tang_dynasty_ming_guang_armor_helmet", NetheritelatetangdynastymingguangarmorItem.Helmet::new);
    public static final DeferredHolder<Item, Item> NETHERITELATETANGDYNASTYMINGGUANGARMOR_CHESTPLATE = REGISTRY.register("netherite_late_tang_dynasty_ming_guang_armor_chestplate", NetheritelatetangdynastymingguangarmorItem.Chestplate::new);
    public static final DeferredHolder<Item, Item> NETHERITELATETANGDYNASTYMINGGUANGARMOR_LEGGINGS = REGISTRY.register("netherite_late_tang_dynasty_ming_guang_armor_leggings", NetheritelatetangdynastymingguangarmorItem.Leggings::new);
    public static final DeferredHolder<Item, Item> NETHERITELATETANGDYNASTYMINGGUANGARMOR_BOOTS = REGISTRY.register("netherite_late_tang_dynasty_ming_guang_armor_boots", NetheritelatetangdynastymingguangarmorItem.Boots::new);

    public static final DeferredHolder<Item, Item> TangDynastyShield = REGISTRY.register("tang_dynasty_shield", TangDynastyShield::new);

    public static final DeferredHolder<Item, Item> DIAMOND_SUANNI_HELMET = REGISTRY.register("diamond_suanni_helmet", DiamondSuanniHelmetItem.Helmet::new);
    public static final DeferredHolder<Item, Item> IRON_SUANNI_HELMET = REGISTRY.register("iron_suanni_helmet", IronSuanniHelmetItem.Helmet::new);
    public static final DeferredHolder<Item, Item> NETHERITE_SUANNI_HELMET = REGISTRY.register("netherite_suanni_helmet", NetheriteSuanniHelmetItem.Helmet::new);
    public static final DeferredHolder<Item, Item> GOLDEN_SUANNI_HELMET = REGISTRY.register("golden_suanni_helmet", GoldenSuanniHelmetItem.Helmet::new);

    public static final DeferredHolder<Item, Item> DIAMOND_BOHAI_HELMET = REGISTRY.register("diamond_bohai_helmet", DiamondBohaiHelmetItem.Helmet::new);
    public static final DeferredHolder<Item, Item> IRON_BOHAI_HELMET = REGISTRY.register("iron_bohai_helmet", IronBohaiHelmetItem.Helmet::new);
    public static final DeferredHolder<Item, Item> NETHERITE_BOHAI_HELMET = REGISTRY.register("netherite_bohai_helmet", NetheriteBohaiHelmetItem.Helmet::new);
    public static final DeferredHolder<Item, Item> GOLDEN_BOHAI_HELMET = REGISTRY.register("golden_bohai_helmet", GoldenBohaiHelmetItem.Helmet::new);

    public static final DeferredHolder<Item, Item> DIAMOND_TANG_DYNASTY_HORSE = REGISTRY.register("diamond_tang_dynasty_horse_armor", () -> new TangDynastyHorseItem(18, ResourceLocation.fromNamespaceAndPath(ChineseweaponsMod.MODID, "textures/entities/horse/armor/diamond_tang_dynasty_horse_armor.png")));
    public static final DeferredHolder<Item, Item> IRON_TANG_DYNASTY_HORSE = REGISTRY.register("iron_tang_dynasty_horse_armor", () -> new TangDynastyHorseItem(8, ResourceLocation.fromNamespaceAndPath(ChineseweaponsMod.MODID, "textures/entities/horse/armor/iron_tang_dynasty_horse_armor.png")));
    public static final DeferredHolder<Item, Item> NETHERITE_TANG_DYNASTY_HORSE = REGISTRY.register("netherite_tang_dynasty_horse_armor", () -> new TangDynastyHorseItem(25, ResourceLocation.fromNamespaceAndPath(ChineseweaponsMod.MODID, "textures/entities/horse/armor/netherite_tang_dynasty_horse_armor.png")));
    public static final DeferredHolder<Item, Item> GOLDEN_TANG_DYNASTY_HORSE = REGISTRY.register("golden_tang_dynasty_horse_armor", () -> new TangDynastyHorseItem(11, ResourceLocation.fromNamespaceAndPath(ChineseweaponsMod.MODID, "textures/entities/horse/armor/golden_tang_dynasty_horse_armor.png")));

    private static DeferredHolder<Item, Item> block(DeferredHolder<Block, Block> block) {
        return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
    }
}
