

package net.mirrorloong.chineseweapons.init;

import net.mirrorloong.chineseweapons.ChineseweaponsMod;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.network.chat.Component;
import net.minecraft.core.registries.Registries;

public class ChineseweaponsModTabs {
	public static final DeferredRegister<CreativeModeTab> REGISTRY = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, ChineseweaponsMod.MODID);
	public static final RegistryObject<CreativeModeTab> CHINESE_WEAPONS = REGISTRY.register("chinese_weapons",
			() -> CreativeModeTab.builder().title(Component.translatable("item_group.chineseweapons.chinese_weapons")).icon(() -> new ItemStack(ChineseweaponsModItems.IRONMOUNTAINCHARACTERARMOR_HELMET.get())).displayItems((parameters, tabData) -> {
				tabData.accept(ChineseweaponsModItems.IRONMOUNTAINCHARACTERARMOR_HELMET.get());
				tabData.accept(ChineseweaponsModItems.IRONMOUNTAINCHARACTERARMOR_CHESTPLATE.get());
				tabData.accept(ChineseweaponsModItems.IRONMOUNTAINCHARACTERARMOR_LEGGINGS.get());
				tabData.accept(ChineseweaponsModItems.IRONMOUNTAINCHARACTERARMOR_BOOTS.get());
				tabData.accept(ChineseweaponsModItems.GOLDENMOUNTAINCHARACTERARMOR_HELMET.get());
				tabData.accept(ChineseweaponsModItems.GOLDENMOUNTAINCHARACTERARMOR_CHESTPLATE.get());
				tabData.accept(ChineseweaponsModItems.GOLDENMOUNTAINCHARACTERARMOR_LEGGINGS.get());
				tabData.accept(ChineseweaponsModItems.GOLDENMOUNTAINCHARACTERARMOR_BOOTS.get());
				tabData.accept(ChineseweaponsModItems.DIAMONDMOUNTAINCHARACTERARMOR_HELMET.get());
				tabData.accept(ChineseweaponsModItems.DIAMONDMOUNTAINCHARACTERARMOR_CHESTPLATE.get());
				tabData.accept(ChineseweaponsModItems.DIAMONDMOUNTAINCHARACTERARMOR_LEGGINGS.get());
				tabData.accept(ChineseweaponsModItems.DIAMONDMOUNTAINCHARACTERARMOR_BOOTS.get());
				tabData.accept(ChineseweaponsModItems.NETHERITEMOUNTAINCHARACTERARMOR_HELMET.get());
				tabData.accept(ChineseweaponsModItems.NETHERITEMOUNTAINCHARACTERARMOR_CHESTPLATE.get());
				tabData.accept(ChineseweaponsModItems.NETHERITEMOUNTAINCHARACTERARMOR_LEGGINGS.get());
				tabData.accept(ChineseweaponsModItems.NETHERITEMOUNTAINCHARACTERARMOR_BOOTS.get());
				tabData.accept(ChineseweaponsModItems.IRONEARLYTANGDYNASTYMINGGUANGARMOR_HELMET.get());
				tabData.accept(ChineseweaponsModItems.IRONEARLYTANGDYNASTYMINGGUANGARMOR_CHESTPLATE.get());
				tabData.accept(ChineseweaponsModItems.IRONEARLYTANGDYNASTYMINGGUANGARMOR_LEGGINGS.get());
				tabData.accept(ChineseweaponsModItems.IRONEARLYTANGDYNASTYMINGGUANGARMOR_BOOTS.get());
				tabData.accept(ChineseweaponsModItems.GOLDENEARLYTANGDYNASTYMINGGUANGARMOR_HELMET.get());
				tabData.accept(ChineseweaponsModItems.GOLDENEARLYTANGDYNASTYMINGGUANGARMOR_CHESTPLATE.get());
				tabData.accept(ChineseweaponsModItems.GOLDENEARLYTANGDYNASTYMINGGUANGARMOR_LEGGINGS.get());
				tabData.accept(ChineseweaponsModItems.GOLDENEARLYTANGDYNASTYMINGGUANGARMOR_BOOTS.get());
				tabData.accept(ChineseweaponsModItems.DIAMONDEARLYTANGDYNASTYMINGGUANGARMOR_HELMET.get());
				tabData.accept(ChineseweaponsModItems.DIAMONDEARLYTANGDYNASTYMINGGUANGARMOR_CHESTPLATE.get());
				tabData.accept(ChineseweaponsModItems.DIAMONDEARLYTANGDYNASTYMINGGUANGARMOR_LEGGINGS.get());
				tabData.accept(ChineseweaponsModItems.DIAMONDEARLYTANGDYNASTYMINGGUANGARMOR_BOOTS.get());
				tabData.accept(ChineseweaponsModItems.NETHERITEEARLYTANGDYNASTYMINGGUANGARMOR_HELMET.get());
				tabData.accept(ChineseweaponsModItems.NETHERITEEARLYTANGDYNASTYMINGGUANGARMOR_CHESTPLATE.get());
				tabData.accept(ChineseweaponsModItems.NETHERITEEARLYTANGDYNASTYMINGGUANGARMOR_LEGGINGS.get());
				tabData.accept(ChineseweaponsModItems.NETHERITEEARLYTANGDYNASTYMINGGUANGARMOR_BOOTS.get());
				tabData.accept(ChineseweaponsModItems.IRONFOOTMENARMOR_HELMET.get());
				tabData.accept(ChineseweaponsModItems.IRONFOOTMENARMOR_CHESTPLATE.get());
				tabData.accept(ChineseweaponsModItems.IRONFOOTMENARMOR_LEGGINGS.get());
				tabData.accept(ChineseweaponsModItems.IRONFOOTMENARMOR_BOOTS.get());
				tabData.accept(ChineseweaponsModItems.GOLDENFOOTMENARMOR_HELMET.get());
				tabData.accept(ChineseweaponsModItems.GOLDENFOOTMENARMOR_CHESTPLATE.get());
				tabData.accept(ChineseweaponsModItems.GOLDENFOOTMENARMOR_LEGGINGS.get());
				tabData.accept(ChineseweaponsModItems.GOLDENFOOTMENARMOR_BOOTS.get());
				tabData.accept(ChineseweaponsModItems.DIAMONDFOOTMENARMOR_HELMET.get());
				tabData.accept(ChineseweaponsModItems.DIAMONDFOOTMENARMOR_CHESTPLATE.get());
				tabData.accept(ChineseweaponsModItems.DIAMONDFOOTMENARMOR_LEGGINGS.get());
				tabData.accept(ChineseweaponsModItems.DIAMONDFOOTMENARMOR_BOOTS.get());
				tabData.accept(ChineseweaponsModItems.NETHERITEFOOTMENARMOR_HELMET.get());
				tabData.accept(ChineseweaponsModItems.NETHERITEFOOTMENARMOR_CHESTPLATE.get());
				tabData.accept(ChineseweaponsModItems.NETHERITEFOOTMENARMOR_LEGGINGS.get());
				tabData.accept(ChineseweaponsModItems.NETHERITEFOOTMENARMOR_BOOTS.get());
				tabData.accept(ChineseweaponsModItems.IRONBLACKCHUIARMOR_HELMET.get());
				tabData.accept(ChineseweaponsModItems.IRONBLACKCHUIARMOR_CHESTPLATE.get());
				tabData.accept(ChineseweaponsModItems.IRONBLACKCHUIARMOR_LEGGINGS.get());
				tabData.accept(ChineseweaponsModItems.IRONBLACKCHUIARMOR_BOOTS.get());
				tabData.accept(ChineseweaponsModItems.GOLDENBLACKCHUIARMOR_HELMET.get());
				tabData.accept(ChineseweaponsModItems.GOLDENBLACKCHUIARMOR_CHESTPLATE.get());
				tabData.accept(ChineseweaponsModItems.GOLDENBLACKCHUIARMOR_LEGGINGS.get());
				tabData.accept(ChineseweaponsModItems.GOLDENBLACKCHUIARMOR_BOOTS.get());
				tabData.accept(ChineseweaponsModItems.DIAMONDBLACKCHUIARMOR_HELMET.get());
				tabData.accept(ChineseweaponsModItems.DIAMONDBLACKCHUIARMOR_CHESTPLATE.get());
				tabData.accept(ChineseweaponsModItems.DIAMONDBLACKCHUIARMOR_LEGGINGS.get());
				tabData.accept(ChineseweaponsModItems.DIAMONDBLACKCHUIARMOR_BOOTS.get());
				tabData.accept(ChineseweaponsModItems.NETHERITEBLACKCHUIARMOR_HELMET.get());
				tabData.accept(ChineseweaponsModItems.NETHERITEBLACKCHUIARMOR_CHESTPLATE.get());
				tabData.accept(ChineseweaponsModItems.NETHERITEBLACKCHUIARMOR_LEGGINGS.get());
				tabData.accept(ChineseweaponsModItems.NETHERITEBLACKCHUIARMOR_BOOTS.get());
				tabData.accept(ChineseweaponsModItems.IRONMIDDLETANGDYNASTYMINGGUANGARMOR_HELMET.get());
				tabData.accept(ChineseweaponsModItems.IRONMIDDLETANGDYNASTYMINGGUANGARMOR_CHESTPLATE.get());
				tabData.accept(ChineseweaponsModItems.IRONMIDDLETANGDYNASTYMINGGUANGARMOR_LEGGINGS.get());
				tabData.accept(ChineseweaponsModItems.IRONMIDDLETANGDYNASTYMINGGUANGARMOR_BOOTS.get());
				tabData.accept(ChineseweaponsModItems.GOLDENMIDDLETANGDYNASTYMINGGUANGARMOR_HELMET.get());
				tabData.accept(ChineseweaponsModItems.GOLDENMIDDLETANGDYNASTYMINGGUANGARMOR_CHESTPLATE.get());
				tabData.accept(ChineseweaponsModItems.GOLDENMIDDLETANGDYNASTYMINGGUANGARMOR_LEGGINGS.get());
				tabData.accept(ChineseweaponsModItems.GOLDENMIDDLETANGDYNASTYMINGGUANGARMOR_BOOTS.get());
				tabData.accept(ChineseweaponsModItems.DIAMONDMIDDLETANGDYNASTYMINGGUANGARMOR_HELMET.get());
				tabData.accept(ChineseweaponsModItems.DIAMONDMIDDLETANGDYNASTYMINGGUANGARMOR_CHESTPLATE.get());
				tabData.accept(ChineseweaponsModItems.DIAMONDMIDDLETANGDYNASTYMINGGUANGARMOR_LEGGINGS.get());
				tabData.accept(ChineseweaponsModItems.DIAMONDMIDDLETANGDYNASTYMINGGUANGARMOR_BOOTS.get());
				tabData.accept(ChineseweaponsModItems.NETHERITEMIDDLETANGDYNASTYMINGGUANGARMOR_HELMET.get());
				tabData.accept(ChineseweaponsModItems.NETHERITEMIDDLETANGDYNASTYMINGGUANGARMOR_CHESTPLATE.get());
				tabData.accept(ChineseweaponsModItems.NETHERITEMIDDLETANGDYNASTYMINGGUANGARMOR_LEGGINGS.get());
				tabData.accept(ChineseweaponsModItems.NETHERITEMIDDLETANGDYNASTYMINGGUANGARMOR_BOOTS.get());
				tabData.accept(ChineseweaponsModItems.IRONLATETANGDYNASTYMINGGUANGARMOR_HELMET.get());
				tabData.accept(ChineseweaponsModItems.IRONLATETANGDYNASTYMINGGUANGARMOR_CHESTPLATE.get());
				tabData.accept(ChineseweaponsModItems.IRONLATETANGDYNASTYMINGGUANGARMOR_LEGGINGS.get());
				tabData.accept(ChineseweaponsModItems.IRONLATETANGDYNASTYMINGGUANGARMOR_BOOTS.get());
				tabData.accept(ChineseweaponsModItems.GOLDENLATETANGDYNASTYMINGGUANGARMOR_HELMET.get());
				tabData.accept(ChineseweaponsModItems.GOLDENLATETANGDYNASTYMINGGUANGARMOR_CHESTPLATE.get());
				tabData.accept(ChineseweaponsModItems.GOLDENLATETANGDYNASTYMINGGUANGARMOR_LEGGINGS.get());
				tabData.accept(ChineseweaponsModItems.GOLDENLATETANGDYNASTYMINGGUANGARMOR_BOOTS.get());
				tabData.accept(ChineseweaponsModItems.DIAMONDLATETANGDYNASTYMINGGUANGARMOR_HELMET.get());
				tabData.accept(ChineseweaponsModItems.DIAMONDLATETANGDYNASTYMINGGUANGARMOR_CHESTPLATE.get());
				tabData.accept(ChineseweaponsModItems.DIAMONDLATETANGDYNASTYMINGGUANGARMOR_LEGGINGS.get());
				tabData.accept(ChineseweaponsModItems.DIAMONDLATETANGDYNASTYMINGGUANGARMOR_BOOTS.get());
				tabData.accept(ChineseweaponsModItems.NETHERITELATETANGDYNASTYMINGGUANGARMOR_HELMET.get());
				tabData.accept(ChineseweaponsModItems.NETHERITELATETANGDYNASTYMINGGUANGARMOR_CHESTPLATE.get());
				tabData.accept(ChineseweaponsModItems.NETHERITELATETANGDYNASTYMINGGUANGARMOR_LEGGINGS.get());
				tabData.accept(ChineseweaponsModItems.NETHERITELATETANGDYNASTYMINGGUANGARMOR_BOOTS.get());
				tabData.accept(ChineseweaponsModItems.IRONFINE_SCALE_ARMOR_HELMET.get());
				tabData.accept(ChineseweaponsModItems.IRONFINE_SCALE_ARMOR_CHESTPLATE.get());
				tabData.accept(ChineseweaponsModItems.IRONFINE_SCALE_ARMOR_LEGGINGS.get());
				tabData.accept(ChineseweaponsModItems.IRONFINE_SCALE_ARMOR_BOOTS.get());
				tabData.accept(ChineseweaponsModItems.GOLDENFINE_SCALE_ARMOR_HELMET.get());
				tabData.accept(ChineseweaponsModItems.GOLDENFINE_SCALE_ARMOR_CHESTPLATE.get());
				tabData.accept(ChineseweaponsModItems.GOLDENFINE_SCALE_ARMOR_LEGGINGS.get());
				tabData.accept(ChineseweaponsModItems.GOLDENFINE_SCALE_ARMOR_BOOTS.get());
				tabData.accept(ChineseweaponsModItems.DIAMONDFINE_SCALE_ARMOR_HELMET.get());
				tabData.accept(ChineseweaponsModItems.DIAMONDFINE_SCALE_ARMOR_CHESTPLATE.get());
				tabData.accept(ChineseweaponsModItems.DIAMONDFINE_SCALE_ARMOR_LEGGINGS.get());
				tabData.accept(ChineseweaponsModItems.DIAMONDFINE_SCALE_ARMOR_BOOTS.get());
				tabData.accept(ChineseweaponsModItems.NETHERITEFINE_SCALE_ARMOR_HELMET.get());
				tabData.accept(ChineseweaponsModItems.NETHERITEFINE_SCALE_ARMOR_CHESTPLATE.get());
				tabData.accept(ChineseweaponsModItems.NETHERITEFINE_SCALE_ARMOR_LEGGINGS.get());
				tabData.accept(ChineseweaponsModItems.NETHERITEFINE_SCALE_ARMOR_BOOTS.get());
				tabData.accept(ChineseweaponsModItems.TANGDYNASTYINFANTRYARMOR_HELMET.get());
				tabData.accept(ChineseweaponsModItems.TANGDYNASTYINFANTRYARMOR_CHESTPLATE.get());
				tabData.accept(ChineseweaponsModItems.TANGDYNASTYINFANTRYARMOR_LEGGINGS.get());
				tabData.accept(ChineseweaponsModItems.TANGDYNASTYINFANTRYARMOR_BOOTS.get());
				tabData.accept(ChineseweaponsModItems.IRON_SUANNI_HELMET.get());
				tabData.accept(ChineseweaponsModItems.GOLDEN_SUANNI_HELMET .get());
				tabData.accept(ChineseweaponsModItems.DIAMOND_SUANNI_HELMET.get());
				tabData.accept(ChineseweaponsModItems.NETHERITE_SUANNI_HELMET.get());
				tabData.accept(ChineseweaponsModItems.IRON_BOHAI_HELMET.get());
				tabData.accept(ChineseweaponsModItems.GOLDEN_BOHAI_HELMET .get());
				tabData.accept(ChineseweaponsModItems.DIAMOND_BOHAI_HELMET.get());
				tabData.accept(ChineseweaponsModItems.NETHERITE_BOHAI_HELMET.get());
				tabData.accept(ChineseweaponsModItems.IRON_TANG_DYNASTY_HORSE.get());
				tabData.accept(ChineseweaponsModItems.GOLDEN_TANG_DYNASTY_HORSE.get());
				tabData.accept(ChineseweaponsModItems.DIAMOND_TANG_DYNASTY_HORSE.get());
				tabData.accept(ChineseweaponsModItems.NETHERITE_TANG_DYNASTY_HORSE.get());
				tabData.accept(ChineseweaponsModItems.WOODEN_DAGGER_AXE.get());
				tabData.accept(ChineseweaponsModItems.STONE_DAGGER_AXE.get());
				tabData.accept(ChineseweaponsModItems.IRON_DAGGER_AXE.get());
				tabData.accept(ChineseweaponsModItems.GOLDEN_DAGGER_AXE.get());
				tabData.accept(ChineseweaponsModItems.DIAMOND_DAGGER_AXE.get());
				tabData.accept(ChineseweaponsModItems.NETHERITE_DAGGER_AXE.get());
				tabData.accept(ChineseweaponsModItems.GREENLOONG_GLAIVE.get());
				tabData.accept(ChineseweaponsModItems.WOODEN_GLAIVE.get());
				tabData.accept(ChineseweaponsModItems.STONE_GLAIVE.get());
				tabData.accept(ChineseweaponsModItems.IRON_GLAIVE.get());
				tabData.accept(ChineseweaponsModItems.GOLDEN_GLAIVE.get());
				tabData.accept(ChineseweaponsModItems.DIAMOND_GLAIVE.get());
				tabData.accept(ChineseweaponsModItems.NETHERITE_GLAIVE.get());
				tabData.accept(ChineseweaponsModItems.WOODEN_SKY_PIERCING_HALBERD.get());
				tabData.accept(ChineseweaponsModItems.STONE_SKY_PIERCING_HALBERD.get());
				tabData.accept(ChineseweaponsModItems.IRON_SKY_PIERCING_HALBERD.get());
				tabData.accept(ChineseweaponsModItems.GOLDEN_SKY_PIERCING_HALBERD.get());
				tabData.accept(ChineseweaponsModItems.DIAMOND_SKY_PIERCING_HALBERD.get());
				tabData.accept(ChineseweaponsModItems.NETHERITE_SKY_PIERCING_HALBERD.get());
				tabData.accept(ChineseweaponsModItems.WOODEN_TANG_DYNASTY_HENG_SABER.get());
				tabData.accept(ChineseweaponsModItems.STONE_TANG_DYNASTY_HENG_SABER.get());
				tabData.accept(ChineseweaponsModItems.IRON_TANG_DYNASTY_HENG_SABER.get());
				tabData.accept(ChineseweaponsModItems.GOLDEN_TANG_DYNASTY_HENG_SABER.get());
				tabData.accept(ChineseweaponsModItems.DIAMOND_TANG_DYNASTY_HENG_SABER.get());
				tabData.accept(ChineseweaponsModItems.NETHERITE_TANG_DYNASTY_HENG_SABER.get());
				tabData.accept(ChineseweaponsModItems.TangDynastyShield.get());
				tabData.accept(ChineseweaponsModBlocks.ARMOR_CASTING_TABLE.get().asItem());
				tabData.accept(ChineseweaponsModBlocks.ANCIENT_GEM_ORE.get().asItem());
				tabData.accept(ChineseweaponsModBlocks.DeepslateANCIENT_GEM_ORE.get().asItem());
				tabData.accept(ChineseweaponsModItems.AncientGem.get());
				tabData.accept(ChineseweaponsModItems.DiamondArmorPieces.get());
				tabData.accept(ChineseweaponsModItems.DiamondArmorPiecesPlate.get());
				tabData.accept(ChineseweaponsModItems.DiamondMountainCharacterArmorPieces.get());
				tabData.accept(ChineseweaponsModItems.DiamondMountainCharacterArmorPiecesPlate.get());
				tabData.accept(ChineseweaponsModItems.GoldenArmorPieces.get());
				tabData.accept(ChineseweaponsModItems.GoldenArmorPiecesPlate.get());
				tabData.accept(ChineseweaponsModItems.GoldenMountainCharacterArmorPieces.get());
				tabData.accept(ChineseweaponsModItems.GoldenMountainCharacterArmorPiecesPlate.get());
				tabData.accept(ChineseweaponsModItems.IronArmorPieces.get());
				tabData.accept(ChineseweaponsModItems.IronArmorPiecesPlate.get());
				tabData.accept(ChineseweaponsModItems.IronMountainCharacterArmorPieces.get());
				tabData.accept(ChineseweaponsModItems.IronMountainCharacterArmorPiecesPlate.get());
				tabData.accept(ChineseweaponsModItems.StoneArmorPieces.get());
				tabData.accept(ChineseweaponsModItems.StoneArmorPiecesPlate.get());
				tabData.accept(ChineseweaponsModItems.EarlyTangDynastyMingGuangArmorforgingStone.get());
				tabData.accept(ChineseweaponsModItems.FootmenArmorforgingStone.get());
				tabData.accept(ChineseweaponsModItems.LateTangDynastyMingGuangArmorforgingStone.get());
				tabData.accept(ChineseweaponsModItems.MiddleTangDynastyMingGuangArmorforgingStone.get());
				tabData.accept(ChineseweaponsModItems.MountainCharacterArmorforgingStone.get());
				tabData.accept(ChineseweaponsModItems.BlackChuiArmorforgingStone.get());
				tabData.accept(ChineseweaponsModItems.FineScaleArmorforgingStone.get());
				tabData.accept(ChineseweaponsModItems.TangDynastyInfantryArmorforgingStone.get());
			}).build());
}
